//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gladiators.Business.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AchievementDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AchievementDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gladiators.Business.Resources.AchievementDescriptions", typeof(AchievementDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrokenFocus (Ур. {0})\nЗа что: За промах четырежды подряд\nЧто даёт: +{1}% к антиувароту.
        /// </summary>
        internal static string BrokenFocus {
            get {
                return ResourceManager.GetString("BrokenFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CritBreaker (Ур. {0})\nЗа что: Получил критический урон дважды подряд\nЧто даёт: +{1}% к антикриту и +{2}% к ХП.
        /// </summary>
        internal static string CritBreaker {
            get {
                return ResourceManager.GetString("CritBreaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Master (Ур. {0})\nЗа что: Сделал 2 критических удара подряд\nЧто даёт: +{1}% к шанс крит. удара и +{2}% к мощности крита.
        /// </summary>
        internal static string CriticalMaster {
            get {
                return ResourceManager.GetString("CriticalMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DexterityBonus  (Ур. {0})\nЗа что:  За очки ловкости\nЧто даёт: +{1}% к увароту и +{2}% к антиувароту.
        /// </summary>
        internal static string DexterityBonus {
            get {
                return ResourceManager.GetString("DexterityBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DodgeMaster (Ур. {0})\nЗа что: Увернулся трижды подряд\nЧто даёт: +{1}% к шансу увернуться +{2}% к урону.
        /// </summary>
        internal static string DodgeMaster {
            get {
                return ResourceManager.GetString("DodgeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominator (Ур. {0})\nЗа что: Выигрыш с HP &gt; 80%\nЧто даёт: +{1}% к HP, +{2}% к урону.
        /// </summary>
        internal static string Dominator {
            get {
                return ResourceManager.GetString("Dominator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntuitionBonus  (Ур. {0})\n За что: За очки  интуиции\nЧто даёт: +{1}% к криту и +{2}% к антикриту.
        /// </summary>
        internal static string IntuitionBonus {
            get {
                return ResourceManager.GetString("IntuitionBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Survivor (Ур. {0})\nЗа что: Выжил с HP &lt; 20%\nЧто даёт: +{1}% к HP.
        /// </summary>
        internal static string LastSurvivor {
            get {
                return ResourceManager.GetString("LastSurvivor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LudusChampion )\nЗа что: Прихоть господина\nЧто даёт: +{1}% ко всем характеристикам и иммунитет к смерти.
        /// </summary>
        internal static string LudusChampion {
            get {
                return ResourceManager.GetString("LudusChampion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Striker (Ур. {0})\nЗа что: Не использовал криты весь бой\nЧто даёт: +{1}% к HP .+{2}% к урону и +{3}% к антикриту.
        /// </summary>
        internal static string PatientStriker {
            get {
                return ResourceManager.GetString("PatientStriker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaminaBonus  (Ур. {0})\nЗа что: За очки выносливости\nЧто даёт: +{1}% к ХП.
        /// </summary>
        internal static string StaminaBonus {
            get {
                return ResourceManager.GetString("StaminaBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StrengthBonus  (Ур. {0})\nЗа что: За очки силы\nЧто даёт: +{1}% к урону.
        /// </summary>
        internal static string StrengthBonus {
            get {
                return ResourceManager.GetString("StrengthBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veteran (Ур. {0})\nЗа что: За победы в боях\nЧто даёт: +{1}% к урону и +{2}% к HP.
        /// </summary>
        internal static string Veteran {
            get {
                return ResourceManager.GetString("Veteran", resourceCulture);
            }
        }
    }
}
