version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: gladiator_pg
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: gladiator_dev
    ports:
      - "5433:5432"